Repository nyu-devops-fall18/products, pull requests merged in 2018-12, with the labels that each got.

#145 Bdd scenario for rating
  app/static/index.html
  app/static/js/rest_api.js
  features/products.feature
Labels: technical debt

#148 BBD scenario add a review
  app/static/index.html
  app/static/js/rest_api.js
  features/products.feature
Labels: technical debt

#152 swagger_list_by_updated_date
  apidocs/swagger_doc.py
Labels: enhancement, technical debt

#153 url bugs for id/name/category fixed
  apidocs/swagger_doc.py
Labels: bug

#160 adding config.py
  config.py
Labels: bug, enhancement, technical debt

#164 README file updated
  README.md
Labels: bug, enhancement

#166 Raising the test coverage
  app/service.py
  tests/test_server.py
Labels: technical debt

#168 Added Test case for Review if no params
  app/service.py
  tests/test_server.py
Labels: technical debt

#169 Refactored code for pylint coverage
  apidocs/swagger_doc.py
  app/__init__.py
  app/model.py
  app/service.py
  app/vcap_services.py
  features/environment.py
  features/steps/product_steps.py
  tests/test_products.py
  tests/test_server.py
Labels: technical debt

#171 Fixing response codes returned by Swagger according to service
  app/service.py
Labels: enhancement

#173 Fixing updateddate fix
  app/model.py
  app/service.py
  tests/test_server.py
Labels: bug, enhancement

#175 Readme file updated
  README.md
Labels: enhancement

#174 Added error handler for 404
  app/service.py
Labels: enhancement, technical debt

#176 Fixed update review bug
  app/service.py
Labels: bug

#177 Change gunicorn number of workers
  Procfile
Labels: bug
