Repository nyu-devops-fall18/products, pull requests merged in 2018-10, with the labels that each got.

#21 Corrected DB code to avoid duplication and created the service to ret…
  app/create_db.py
  app/productmodel.py
  app/productservice.py
  run.py
Labels: enhancement

#26 Added functionality to update rating of a product based on average of all past ratings
  __init__.py
  app/create_db.py
  app/productmodel.py
  app/productservice.py
  productmodel.py
  productservice.py
Labels: enhancement

#30 List by name and by category bugs fixed. Run.py file updated. product…
  app/__init__.py
  app/productmodel.py
  app/productservice.py
  run.py
Labels: enhancement

#29 Fixed Vagrant and local browser integration bug while removing extra all() function
  app/productmodel.py
  run.py
Labels: technical debt

#32 Added the delete product functionality
  app/productmodel.py
  app/productservice.py
Labels: enhancement

#33 Changed update rating to update product by id
  app/productmodel.py
  app/productservice.py
Labels: enhancement

#35 Added List By ID
  app/productservice.py
Labels: enhancement

#37 Added error handlers for different response codes
  app/productservice.py
Labels: enhancement

#39 Fixed the messages and response along with status code for Update product service
  app/productservice.py
Labels: bug

#46 Fixed bug and Deleted extra test file
  tests/test_pets.py
  tests/test_server.py
Labels: bug

#47 Fixed import error in test_products
  tests/test_products.py
Labels: bug

#48 Added tests for find by name, id and category
  tests/test_products.py
Labels: enhancement

#49 Updated test server and service file to match
  app/productservice.py
  tests/test_server.py
Labels: bug

#50 Added all tests in test_products.py
  tests/test_products.py
Labels: enhancement

#52 Nosetests
  tests/test_products.py
  tests/test_server.py
Labels: bug

#53 Added setup config file for nosetests
  setup.cfg
Labels: technical debt

#57 Added coverage for missing arg validation error
  tests/test_products.py
Labels: enhancement

#59 Fixed the flask app running error due to creation of mock data
  app/create_db.py
Labels: bug

#60 Added price range unit tests
  tests/test_products.py
  tests/test_server.py
Labels: technical debt

#61 Added 405 code coverage
  tests/test_server.py
Labels: enhancement

#62 Increased coverage
  app/productservice.py
  tests/test_server.py
Labels: enhancement

#64 List by date
  app/productmodel.py
  app/productservice.py
  tests/test_products.py
  tests/test_server.py
Labels: enhancement

#66 Added the url's for all functions on Index Page
  app/productservice.py
Labels: enhancement

#75 Added Travis CI YML file and updated Readme.MD
  .travis.yml
  README.md
Labels: technical debt

#77 Added Codecov badge to the README.md file
  README.md
Labels: technical debt

#78 Added codecov label to README.md
  .travis.yml
Labels: technical debt

#79 Fixing Delete service to return a logical response and 204 as status code always
  app/productservice.py
Labels: bug

#80 Fixed filenames for service and model
  app/create_db.py
  app/model.py
  app/service.py
  run.py
  tests/test_products.py
  tests/test_server.py
Labels: bug
