Repository nyu-devops-fall18/products, pull requests merged in 2018-11, with the labels that each got.

#90 Improved the Service.py code cover to 97%
  app/service.py
  tests/test_server.py
Labels: technical debt

#82 Add rating module to Products service as an action
  app/service.py
  tests/test_products.py
  tests/test_server.py
Labels: bug, enhancement

#100 README service description and run steps added
  README.md
Labels: bug

#98 Increased codecov by changing directory structure
  create_db.py
  run.py
Labels: technical debt

#108 Adding BDD to Products service
  Vagrantfile
  app/model.py
  app/service.py
  app/static/css/blue_bootstrap.min.css
  app/static/css/darkly_bootstrap.min.css
  app/static/css/flatly_bootstrap.min.css
  app/static/css/slate_bootstrap.min.css
  app/static/images/newapp-icon.png
  app/static/index.html
  app/static/js/jquery-3.1.1.min.js
  app/static/js/rest_api.js
  features/environment.py
  features/products.feature
  features/steps/product_steps.py
  requirements.txt
  tests/test_server.py
Labels: technical debt

#110 RESTplus added to requirement list
  requirements.txt
Labels: bug

#115 Added BDD Scenario for deleting a product
  app/static/js/rest_api.js
  features/products.feature
  manifest.yml
Labels: technical debt

#117 Adding ElephantDB to product service
  .gitignore
  app/__init__.py
  app/static/index.html
  app/static/js/rest_api.js
  create_db.py
  db/.keep
  features/products.feature
  features/steps/product_steps.py
  manifest.yml
  requirements.txt
Labels: enhancement, technical debt

#118 Changed manifest
  manifest.yml
Labels: technical debt

#119 Added Test step URL for bluemix
  features/environment.py
  features/steps/product_steps.py
Labels: technical debt

#120 Integration testing
  app/__init__.py
  features/environment.py
  features/steps/product_steps.py
Labels: bug

#121 Swagger Doc
  apidocs/swagger_doc.py
Labels: enhancement, technical debt

#130 Fixed Review to take id as a param
  app/service.py
  tests/test_server.py
Labels: bug

#131 Added Review for Swagger
  apidocs/swagger_doc.py
Labels: enhancement, technical debt

#132 id/name/category are all working now.
  apidocs/swagger_doc.py
Labels: technical debt

#134 Trying Bluemix Integration with HTTP
  features/environment.py
  features/steps/product_steps.py
Labels: bug

#135 Fixing BDD for rating
  features/environment.py
  features/steps/product_steps.py
Labels: bug

#136 Fixing BDD
  features/steps/product_steps.py
Labels: bug

#137 Fixing BDD
  features/steps/product_steps.py
Labels: bug

#139 PROD pipeline
  manifest.yml
Labels: technical debt
